name: uCarsRace
main: net.stormdev.ucars.race.main
version: 12
softdepend: [Vault]
depend: [uCars]
commands:
   urace:
        description: This is the setup of racetracks and admin commands
        usage: /<command>
        permission: ucarsrace.admin
        permission-message: You don't have access to this command
        default: op