name: uCarsRace
main: net.stormdev.ucars.race.main
version: 0.1-BETA
softdepend: [Vault]
depend: [uCars]
commands:
   raceAdmin:
        description: This is the setup of racetracks and admin commands
        usage: /<command> [Create <TrackName> <Laps>] [Delete <TrackName>] [List (Page)]
        permission: ucarsrace.admin
        permission-message: You don't have access to this command
        default: op
   urace:
        description: This is the playing of race tracks
        usage: /<command> [List (Page)] [Join (Track/"auto")] [Leave] [Queues]
        permission: ucarsrace.race
        permission-message: You don't have access to this command
        default: true